FROM nginx:alpine

# Copy dashboard files
COPY front/index.html /usr/share/nginx/html/
COPY front/cp_manager.html /usr/share/nginx/html/
COPY front/cp_manager_terminal.html /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]